insert into admin (name, surname, address, city, country, email, password, explanation, money, number) values ('Wynnie', 'Marians', '6 Texas Crossing', 'Jiabeiyan', 'China', 'wmarians0@skyrock.com', 'PHchtvkk7', 'est congue elementum in hac habitasse', 583, '813-989-0158');
insert into admin (name, surname, address, city, country, email, password, explanation, money, number) values ('Jule', 'M''Quhan', '67 Forest Pass', 'Pallasovka', 'Russia', 'jmquhan1@eventbrite.com', 'AI0fKItOI', 'nulla sed vel enim sit', 1753, '248-360-9216');
insert into admin (name, surname, address, city, country, email, password, explanation, money, number) values ('Rosamond', 'Huccaby', '2216 Pankratz Road', 'Lutou', 'China', 'rhuccaby2@mac.com', 'b5ODA4hOqSF6', 'elementum ligula vehicula consequat', 1581, '224-913-2995');
insert into admin (name, surname, address, city, country, email, password, explanation, money, number) values ('Derk', 'Plett', '82 Southridge Crossing', 'Buchou', 'China', 'dplett3@yale.edu', 'yXexiEA', 'posuere cubilia curae nulla dapibus dolor vel', 675, '703-565-6821');
insert into admin (name, surname, address, city, country, email, password, explanation, money, number) values ('Ashia', 'Jumont', '5499 Bartelt Drive', 'Santa Praxedes', 'Philippines', 'ajumont4@delicious.com', 'I6JMiJp', 'est donec odio justo sollicitudin ut suscipit', 619, '334-758-1680');
insert into admin (name, surname, address, city, country, email, password, explanation, money, number) values ('Julietta', 'Cullington', '8 Northwestern Point', 'Graz', 'Austria', 'jcullington5@last.fm', 'FUmllYV', 'ut erat curabitur gravida nisi at', 945, '984-137-4429');
insert into admin (name, surname, address, city, country, email, password, explanation, money, number) values ('Darlene', 'Woolcocks', '61049 Duke Drive', 'Cihaurbeuti', 'Indonesia', 'dwoolcocks6@dell.com', 'CxpqT4tp', 'pulvinar sed nisl nunc rhoncus dui', 418, '121-388-8541');

insert into client (name, surname, address, city, country, email, password, explanation, penalty, number) values ('Washington', 'Eggar', '24832 Katie Avenue', 'Sena Madureira', 'Brazil', 'weggar0@last.fm', '0LLEye', 'eu orci mauris lacinia', 1, '200-105-3377');
insert into client (name, surname, address, city, country, email, password, explanation, penalty, number) values ('Gilberta', 'Mc Gorley', '8 Eagle Crest Lane', 'Kalapagada', 'Indonesia', 'gmcgorley1@google.co.uk', 'CfeDpUgYV', 'tortor risus dapibus augue vel accumsan', 1, '396-623-0749');
insert into client (name, surname, address, city, country, email, password, explanation, penalty, number) values ('Zack', 'Arr', '7 Pearson Road', 'Kuala Terengganu', 'Malaysia', 'zarr2@moonfruit.com', 'AqPQ7kMAw0XT', 'amet lobortis sapien sapien', 2, '506-992-9704');
insert into client (name, surname, address, city, country, email, password, explanation, penalty, number) values ('Tandi', 'O''Hogertie', '8 Homewood Terrace', 'Magallon Cadre', 'Philippines', 'tohogertie3@usda.gov', 'fhqkCx', 'ornare consequat lectus in', 1, '607-868-4032');
insert into client (name, surname, address, city, country, email, password, explanation, penalty, number) values ('Madelon', 'Showler', '226 Mosinee Crossing', 'Kiruna', 'Sweden', 'mshowler4@chicagotribune.com', 'KebqbOYs8Zp', 'iaculis justo in hac', 0, '609-933-8055');
insert into client (name, surname, address, city, country, email, password, explanation, penalty, number) values ('Maryjo', 'Scopes', '7 Leroy Crossing', 'Karakulino', 'Russia', 'mscopes5@amazon.com', 'II2lgvQGJ0ii', 'consectetuer adipiscing elit proin', 2, '101-938-9772');
insert into client (name, surname, address, city, country, email, password, explanation, penalty, number) values ('Susette', 'Vondrach', '54539 Thompson Drive', 'Veyno', 'Belarus', 'svondrach6@webmd.com', 'PC247L', 'in tempor turpis nec euismod scelerisque quam', 2, '187-688-8289');

insert into cottage_owner (name, surname, address, city, country, email, password, explanation, number) values ('Bev', 'Kumar', '404 Quincy Trail', 'Patrol', 'Indonesia', 'bkumar0@quantcast.com', 'A7fP2T', 'nullam sit amet turpis', '774-188-1464');
insert into cottage_owner (name, surname, address, city, country, email, password, explanation, number) values ('Damaris', 'Kamen', '7 Butternut Trail', 'Zhangdian', 'China', 'dkamen1@rakuten.co.jp', 'BuJdMYXzNoCh', 'faucibus orci luctus et ultrices posuere', '776-398-5991');
insert into cottage_owner (name, surname, address, city, country, email, password, explanation, number) values ('Isidro', 'Lenchenko', '7346 Toban Alley', 'Longlisuo', 'China', 'ilenchenko2@netvibes.com', 'sFeTCgTOs9y6', 'sem duis aliquam convallis nunc', '378-695-9002');
insert into cottage_owner (name, surname, address, city, country, email, password, explanation, number) values ('Salvatore', 'Bilbery', '23 Moose Street', 'Jingkou', 'China', 'sbilbery3@linkedin.com', '0TfgVmJ', 'quis turpis sed ante vivamus tortor duis', '574-163-7535');
insert into cottage_owner (name, surname, address, city, country, email, password, explanation, number) values ('Clair', 'Sitch', '0017 Towne Point', 'Gamut', 'Philippines', 'csitch4@homestead.com', 'OOOdqrVJHRi', 'non ligula pellentesque ultrices phasellus id', '215-334-8021');
insert into cottage_owner (name, surname, address, city, country, email, password, explanation, number) values ('Penelope', 'Lawday', '220 Dunning Alley', 'Kamień Pomorski', 'Poland', 'plawday5@virginia.edu', 'FqNtq5cX', 'potenti cras in purus', '756-679-5373');
insert into cottage_owner (name, surname, address, city, country, email, password, explanation, number) values ('Kip', 'Cheesman', '56475 Steensland Junction', 'Chagou', 'China', 'kcheesman6@furl.net', 'LEjMnSA2UZ0', 'diam in magna bibendum imperdiet nullam orci', '682-734-4013');

insert into boat_owner (name, surname, address, city, country, email, password, explanation, number, biography) values ('Gabriel', 'Semmens', '7 Macpherson Crossing', 'Shchëkino', 'Russia', 'gsemmens0@baidu.com', '5Mza0z', 'nullam orci pede venenatis non', '564-182-4460', 'interdum venenatis turpis enim blandit mi in');
insert into boat_owner (name, surname, address, city, country, email, password, explanation, number, biography) values ('Derward', 'Chaman', '9113 Ridgeview Drive', 'Atbasar', 'Kazakhstan', 'dchaman1@blogger.com', 'PhlzzeNZSpV', 'vivamus in felis eu sapien cursus', '910-482-2549', 'neque libero convallis eget eleifend luctus');
insert into boat_owner (name, surname, address, city, country, email, password, explanation, number, biography) values ('Odille', 'Burdge', '448 Grim Hill', 'Szolnok', 'Hungary', 'oburdge2@alexa.com', '73LEwbOYnx', 'in est risus auctor sed tristique', '244-337-6987', 'nonummy integer non velit donec diam');
insert into boat_owner (name, surname, address, city, country, email, password, explanation, number, biography) values ('Averil', 'Stodd', '2 Maywood Plaza', 'Sangmu', 'China', 'astodd3@desdev.cn', 'QoU8STTzE', 'malesuada in imperdiet et commodo', '836-326-5788', 'in porttitor pede justo eu massa donec');
insert into boat_owner (name, surname, address, city, country, email, password, explanation, number, biography) values ('Lalo', 'Hynd', '4 Meadow Ridge Center', 'Zhongtang', 'China', 'lhynd4@deviantart.com', 'VoN9GWevJ5', 'nibh in lectus pellentesque at', '187-963-4731', 'sapien cursus vestibulum proin eu mi');
insert into boat_owner (name, surname, address, city, country, email, password, explanation, number, biography) values ('Lutero', 'Zorzenoni', '181 Emmet Court', 'Slovenski Javornik', 'Slovenia', 'lzorzenoni5@uol.com.br', 'uDDsc4j', 'erat id mauris vulputate', '755-593-9718', 'integer pede justo lacinia');
insert into boat_owner (name, surname, address, city, country, email, password, explanation, number, biography) values ('Clevey', 'Couvert', '2 Bay Pass', 'Warlubie', 'Poland', 'ccouvert6@multiply.com', 'yfGmnnB3W7tQ', 'ut dolor morbi vel lectus', '160-137-8460', 'primis in faucibus orci luctus et ultrices');

insert into instructor (name, surname, address, city, country, email, password, explanation, number, short_biography) values ('Hollyanne', 'Evason', '5 Blaine Court', 'Satita', 'Syria', 'hevason0@unc.edu', '2Pw3GomL', 'varius nulla facilisi cras non velit nec', '184-505-2872', 'congue diam id ornare');
insert into instructor (name, surname, address, city, country, email, password, explanation, number, short_biography) values ('Job', 'Bruyett', '145 Hudson Circle', 'Serrana', 'Brazil', 'jbruyett1@hao123.com', 'ypmzmZ', 'eu interdum eu tincidunt', '343-751-1474', 'nisl duis ac nibh fusce lacus');
insert into instructor (name, surname, address, city, country, email, password, explanation, number, short_biography) values ('Brynne', 'Kun', '11844 Bay Lane', 'Konga', 'Indonesia', 'bkun2@auda.org.au', 'UdIV9X', 'feugiat et eros vestibulum ac est', '281-946-1431', 'dapibus at diam nam tristique tortor');
insert into instructor (name, surname, address, city, country, email, password, explanation, number, short_biography) values ('Kate', 'Backes', '8144 Cherokee Circle', 'Lipno', 'Poland', 'kbackes3@mashable.com', '4WmKmbmc4m5', 'justo pellentesque viverra pede', '492-126-5918', 'eu felis fusce posuere felis sed');
insert into instructor (name, surname, address, city, country, email, password, explanation, number, short_biography) values ('Jaye', 'Speek', '096 Chive Point', 'Ubatã', 'Brazil', 'jspeek4@archive.org', 'yH4nFgGW', 'id justo sit amet', '843-342-2954', 'consequat morbi a ipsum');
insert into instructor (name, surname, address, city, country, email, password, explanation, number, short_biography) values ('Rosalyn', 'Brandt', '68018 Hudson Plaza', 'El Cerrito', 'Mexico', 'rbrandt5@dailymotion.com', 'o7ATWWAFA', 'nulla suscipit ligula in lacus', '919-337-2121', 'eros elementum pellentesque quisque porta volutpat erat');
insert into instructor (name, surname, address, city, country, email, password, explanation, number, short_biography) values ('Mano', 'Salmons', '210 Meadow Valley Point', 'Jabat', 'Marshall Islands', 'msalmons6@hao123.com', 'B8ktNE6', 'sapien arcu sed augue', '756-943-8916', 'pellentesque eget nunc donec quis orci');

insert into boat (name, address, capacity, max_speed, motor_power, price, promo_description, status, type, boat_owner_id, length, num_motors) values ('Bennie', '08 Stang Center', 3, 62, 9, 66, 'quis lectus suspendisse potenti in eleifend quam', 'free', 'deck', 5, 9, 1);
insert into boat (name, address, capacity, max_speed, motor_power, price, promo_description, status, type, boat_owner_id, length, num_motors) values ('Elana', '8540 Lyons Way', 4, 25, 10, 134, 'dictumst maecenas ut massa', 'free', 'deck', 6, 8, 3);
insert into boat (name, address, capacity, max_speed, motor_power, price, promo_description, status, type, boat_owner_id, length, num_motors) values ('Winnifred', '7626 Garrison Hill', 1, 49, 4, 149, 'amet erat nulla tempus vivamus in', 'booked', 'catamaran', 2, 13, 2);
insert into boat (name, address, capacity, max_speed, motor_power, price, promo_description, status, type, boat_owner_id, length, num_motors) values ('Roxane', '65 Anderson Trail', 5, 55, 1, 84, 'orci luctus et ultrices posuere', 'free', 'catamaran', 3, 13, 3);
insert into boat (name, address, capacity, max_speed, motor_power, price, promo_description, status, type, boat_owner_id, length, num_motors) values ('Fania', '9 Oneill Way', 1, 25, 4, 50, 'a odio in hac habitasse platea', 'free', 'catamaran', 2, 13, 3);
insert into boat (name, address, capacity, max_speed, motor_power, price, promo_description, status, type, boat_owner_id, length, num_motors) values ('Grantham', '29 Knutson Avenue', 4, 22, 8, 147, 'cursus urna ut tellus', 'free', 'catamaran', 2, 14, 2);
insert into boat (name, address, capacity, max_speed, motor_power, price, promo_description, status, type, boat_owner_id, length, num_motors) values ('Lauritz', '712 Hanson Place', 2, 36, 5, 54, 'nisl duis bibendum felis sed', 'free', 'deck', 6, 5, 2);

insert into cottage (name, address, price, promo_description, status, cottage_owner_id) values ('Roma', '74 Petterle Hill', 114, 'purus eu magna vulputate', 'free', 4);
insert into cottage (name, address, price, promo_description, status, cottage_owner_id) values ('Van', '19 Killdeer Park', 119, 'consectetuer adipiscing elit proin', 'booked', 4);
insert into cottage (name, address, price, promo_description, status, cottage_owner_id) values ('Robinetta', '0 Evergreen Drive', 34, 'et ultrices posuere cubilia', 'free', 5);
insert into cottage (name, address, price, promo_description, status, cottage_owner_id) values ('Rahal', '6623 Fulton Road', 117, 'non lectus aliquam sit amet diam', 'booked', 6);
insert into cottage (name, address, price, promo_description, status, cottage_owner_id) values ('Ravid', '9963 Grasskamp Hill', 144, 'a odio in hac habitasse', 'free', 3);
insert into cottage (name, address, price, promo_description, status, cottage_owner_id) values ('Abigael', '405 Walton Terrace', 119, 'at nunc commodo placerat praesent', 'free', 6);
insert into cottage (name, address, price, promo_description, status, cottage_owner_id) values ('Upton', '588 Donald Court', 131, 'suscipit a feugiat et', 'booked', 7);

insert into fishing_class (name, address, price, promo_description, status, instructor_id, cancellation_condition) values ('Tomi', '139 Fair Oaks Point', 134, 'justo etiam pretium iaculis justo in', 'free', 3, 14);
insert into fishing_class (name, address, price, promo_description, status, instructor_id, cancellation_condition) values ('Min', '028 Esch Junction', 104, 'ut volutpat sapien arcu sed augue aliquam', 'free', 7, 4);
insert into fishing_class (name, address, price, promo_description, status, instructor_id, cancellation_condition) values ('Kale', '09 Spohn Way', 129, 'odio cras mi pede malesuada in', 'free', 7, 5);
insert into fishing_class (name, address, price, promo_description, status, instructor_id, cancellation_condition) values ('Ann-marie', '7 Bluejay Junction', 107, 'justo in hac habitasse platea dictumst etiam', 'free', 7, 11);
insert into fishing_class (name, address, price, promo_description, status, instructor_id, cancellation_condition) values ('Ad', '2 Warner Parkway', 117, 'erat curabitur gravida nisi at nibh', 'booked', 3, 6);
insert into fishing_class (name, address, price, promo_description, status, instructor_id, cancellation_condition) values ('Salli', '850 Almo Pass', 148, 'risus praesent lectus vestibulum quam', 'booked', 3, 11);
insert into fishing_class (name, address, price, promo_description, status, instructor_id, cancellation_condition) values ('Lesley', '3056 Vidon Court', 62, 'nunc vestibulum ante ipsum primis in', 'free', 2, 7);

insert into cottage_room (number, num_beds, cottage_id) values (11, 2, 2);
insert into cottage_room (number, num_beds, cottage_id) values (13, 6, 5);
insert into cottage_room (number, num_beds, cottage_id) values (19, 2, 2);
insert into cottage_room (number, num_beds, cottage_id) values (10, 7, 4);
insert into cottage_room (number, num_beds, cottage_id) values (15, 6, 6);
insert into cottage_room (number, num_beds, cottage_id) values (9, 3, 4);
insert into cottage_room (number, num_beds, cottage_id) values (7, 3, 4);

